{{- range list "actor" "gateway" "control" }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{ . }}
spec:
  minAvailable: {{ (index $.Values .).minAvailable }}
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      {{- include "signaling.labels" (dict "root" $ "component" .) | nindent 6 }}
{{- end }}
