package io.webrtc.signaling.rpc;
import static org.assertj.core.api.Assertions.*;
import io.webrtc.signaling.actors.relay.*;
import io.webrtc.signaling.protocol.*;
import io.webrtc.signaling.protocol.Identity.*;
import io.webrtc.signaling.storage.AuthoritySql;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import org.junit.jupiter.api.Test;
/** TEST_ONLY native projections isolate cache ownership; real PostgreSQL coverage is separate. */
class NativeRelayRoundCacheTest {
    final CallId call=CallId.create("c001",1);final AtomicLong mono=new AtomicLong(1);final AtomicBoolean trusted=new AtomicBoolean(true);
    final AuthoritySql.GroupToken group=new AuthoritySql.GroupToken("c001",1,1,175,2,"TEST_ONLY_OWNER",UUID.randomUUID());
    final AuthenticatedSession sender=session("sender"),recipient=session("recipient");
    AuthenticatedSession session(String id){return new AuthenticatedSession(new UserId("TEST_ONLY_"+id),new SessionKey("TEST_ONLY",id),new SessionIncarnation(UUID.randomUUID()),1,UUID.randomUUID());}
    CallCommand command(){return new CallCommand(SignalEnvelope.Type.OFFER,sender,new RequestId(UUID.randomUUID()),call,CommandScope.call(call),null,new NegotiationId(17),new IceGeneration(29),"{\"sdp\":\"v=0\"}","a".repeat(64));}
    NativeRelayAuthorization.AuthorizedRound round(){var activation=UUID.randomUUID();long until=mono.get()+Duration.ofSeconds(3).toNanos();var snapshot=new RelayAuthorizationCache.Snapshot(call,activation,7,17,29,"CONNECTING",sender,recipient,group,mono.get(),until,until,until,until);var grant=new NegotiationRelay.Grant(call,activation,7,17,29,sender,recipient,mono.get()+Duration.ofSeconds(20).toNanos(),group);return new NativeRelayAuthorization.AuthorizedRound(snapshot,grant,Instant.now().plusSeconds(3),new RelayDestination("c001","TEST_ONLY_GW",UUID.randomUUID(),recipient));}
    @Test void warmFramesPreserveOriginalRoundRouteAndAuthorityWithoutAnotherNativeRead(){var calls=new AtomicInteger();var original=round();try(var cache=new NativeRelayRoundCache(2,1,(c,p,b)->{calls.incrementAndGet();return new RpcOperation<>(CompletableFuture.completedFuture(original),CompletableFuture.completedFuture(null));},mono::get,trusted::get,c->Optional.of(group))){var first=cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1));assertThat(first.logical().toCompletableFuture().join()).isSameAs(original);first.physicalCompletion().toCompletableFuture().join();mono.addAndGet(Duration.ofSeconds(1).toNanos());var second=cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1));assertThat(second.logical().toCompletableFuture().join()).isSameAs(original);assertThat(calls).hasValue(1);assertThat(cache.cached(command())).contains(original);assertThat(cache.size()).isEqualTo(1);trusted.set(false);assertThat(cache.cached(command())).isEmpty();assertThat(cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1)).logical().toCompletableFuture()).isCompletedExceptionally();assertThat(calls).hasValue(1);}}
    @Test void coalescedConsumerTimeoutAndDrainKeepOriginalRefreshUntilActualCleanup()throws Exception {var calls=new AtomicInteger();var logical=new CompletableFuture<NativeRelayAuthorization.AuthorizedRound>();var physical=new CompletableFuture<Void>();var cache=new NativeRelayRoundCache(2,1,(c,p,b)->{calls.incrementAndGet();return new RpcOperation<>(logical,physical);},mono::get,trusted::get,c->Optional.of(group));var first=cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1));var second=cache.load(command(),"TEST_ONLY_PROOF",Duration.ofMillis(10));assertThatThrownBy(()->second.logical().toCompletableFuture().get(1,TimeUnit.SECONDS)).hasCauseInstanceOf(TimeoutException.class);assertThat(calls).hasValue(1);assertThat(cache.pending()).isEqualTo(1);logical.complete(round());assertThat(first.logical().toCompletableFuture().get(1,TimeUnit.SECONDS)).isNotNull();assertThat(first.physicalCompletion().toCompletableFuture()).isNotDone();var drain=cache.drain();assertThat(drain.toCompletableFuture()).isNotDone();physical.complete(null);drain.toCompletableFuture().get(1,TimeUnit.SECONDS);assertThat(cache.pending()).isZero();assertThat(cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1)).logical().toCompletableFuture()).isCompletedExceptionally();assertThat(calls).hasValue(1);}
    @Test void invalidatedLateNativeRoundCannotRestoreMetadataOrAdmission()throws Exception {var logical=new CompletableFuture<NativeRelayAuthorization.AuthorizedRound>();var physical=new CompletableFuture<Void>();try(var cache=new NativeRelayRoundCache(2,1,(c,p,b)->new RpcOperation<>(logical,physical),mono::get,trusted::get,c->Optional.of(group))){var work=cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1));cache.invalidate(call);assertThat(work.logical().toCompletableFuture()).isCompletedExceptionally();logical.complete(round());assertThat(cache.size()).isZero();assertThat(cache.pending()).isEqualTo(1);physical.complete(null);work.physicalCompletion().toCompletableFuture().get(1,TimeUnit.SECONDS);assertThat(cache.pending()).isZero();assertThat(cache.size()).isZero();}}
    @Test void warmIceAuthorityCannotTurnAnswererIntoOfferer(){var nativeRound=round();var switched=new NativeRelayAuthorization.AuthorizedRound(nativeRound.authorization(),new NegotiationRelay.Grant(call,nativeRound.grant().activationId(),7,17,29,recipient,sender,nativeRound.grant().untilNanos(),group),nativeRound.authorizationUntil(),nativeRound.destination());var reads=new AtomicInteger();try(var cache=new NativeRelayRoundCache(2,1,(c,p,b)->{reads.incrementAndGet();return new RpcOperation<>(CompletableFuture.completedFuture(switched),CompletableFuture.completedFuture(null));},mono::get,trusted::get,c->Optional.of(group))){var offer=command();var ice=new CallCommand(SignalEnvelope.Type.ICE_CANDIDATES,sender,offer.requestId(),call,CommandScope.call(call),null,offer.negotiationId(),offer.iceGeneration(),"{}",offer.intentHash());assertThat(cache.load(ice,"TEST_ONLY_PROOF",Duration.ofSeconds(1)).logical().toCompletableFuture().join()).isSameAs(switched);assertThat(cache.cached(offer)).isEmpty();assertThat(cache.cached(ice)).contains(switched);assertThat(cache.load(offer,"TEST_ONLY_PROOF",Duration.ofSeconds(1)).logical().toCompletableFuture()).isCompletedExceptionally();assertThat(reads).hasValue(1);}}

    @Test void originalNegotiationDeadlineCannotBeExtendedByLongerActiveAuthorization(){var original=round();var shorter=new NativeRelayAuthorization.AuthorizedRound(original.authorization(),new NegotiationRelay.Grant(call,original.grant().activationId(),7,17,29,sender,recipient,mono.get()+Duration.ofMillis(100).toNanos(),group),original.authorizationUntil(),original.destination());var reads=new AtomicInteger();try(var cache=new NativeRelayRoundCache(2,1,(c,p,b)->{reads.incrementAndGet();return new RpcOperation<>(CompletableFuture.completedFuture(shorter),CompletableFuture.completedFuture(null));},mono::get,trusted::get,c->Optional.of(group))){assertThat(cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1)).logical().toCompletableFuture().join()).isSameAs(shorter);mono.addAndGet(Duration.ofMillis(200).toNanos());assertThat(cache.cached(command())).isEmpty();assertThat(cache.load(command(),"TEST_ONLY_PROOF",Duration.ofSeconds(1)).logical().toCompletableFuture()).isCompletedExceptionally();assertThat(reads).hasValue(1);}}

}
