package io.webrtc.signaling.observability;
import static org.assertj.core.api.Assertions.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
class TelemetryContractTest {
    @Test void rawSecretsAndUnknownFreeTextNeverReachStructuredLogsOrTraceAttributes(){var raw=Map.of("authorization","Bearer aaa.bbb.ccc","sdp","v=0\r\na=ice-pwd:secret","iceCandidate","candidate:1 1 UDP 1 10.0.0.1 9999 typ host","turnCredentials","turn-secret","message","password=another-secret","operation","INVITE");var safe=SensitiveDataRedactor.redact(raw).toString();assertThat(safe).doesNotContain("aaa.bbb.ccc","v=0","ice-pwd","10.0.0.1","turn-secret","another-secret").contains("INVITE");assertThat(TraceContext.attributes(raw).toString()).doesNotContain("aaa.bbb.ccc","secret","10.0.0.1");}
    @Test void operationOutcomesAreSeparatedAndPrometheusHasPercentileHistograms(){try(var metrics=new SignalingMetrics("c001",SignalingMetrics.Plane.ACTOR,"a".repeat(64))){metrics.operation(SignalingMetrics.Operation.INVITE,SignalingMetrics.Outcome.USER_BUSY,Duration.ofMillis(4));metrics.operation(SignalingMetrics.Operation.INVITE,SignalingMetrics.Outcome.UNAVAILABLE,Duration.ofMillis(8));String scrape=metrics.scrape();assertThat(scrape).contains("signaling_operation_total","BUSINESS","SERVICE_FAILURE","signaling_operation_latency_seconds_bucket","le=\"0.02\"","le=\"1.0\"","le=\"2.0\"").doesNotContain("userId","callId","requestId");assertThat(metrics.businessOutcomes()).isEqualTo(1);assertThat(metrics.serviceFailures()).isEqualTo(1);}}
    @Test void recoverySlisHaveIndependentEligibleDenominatorsAndMissingTelemetryCannotManufactureSuccess(){try(var metrics=new SignalingMetrics("c001",SignalingMetrics.Plane.ACTOR,"b".repeat(64))){for(var sli:SignalingMetrics.RecoverySli.values())metrics.recovery(sli,true,sli!=SignalingMetrics.RecoverySli.MEDIA_CONTINUITY);metrics.recovery(SignalingMetrics.RecoverySli.MEDIA_CONTINUITY,false,true);assertThat(metrics.ratio(SignalingMetrics.RecoverySli.WORKFLOW_CONVERGENCE)).isEqualTo(1);assertThat(metrics.ratio(SignalingMetrics.RecoverySli.ACTIVE_CALL_PRESERVATION)).isEqualTo(1);assertThat(metrics.ratio(SignalingMetrics.RecoverySli.SIGNALING_REATTACHMENT)).isEqualTo(1);assertThat(metrics.ratio(SignalingMetrics.RecoverySli.MEDIA_CONTINUITY)).isZero();assertThat(metrics.scrape()).contains("WORKFLOW_CONVERGENCE","ACTIVE_CALL_PRESERVATION","SIGNALING_REATTACHMENT","MEDIA_CONTINUITY");}}
    @Test void metricDimensionsAndTraceParentAreStrictlyBounded(){assertThatThrownBy(()->new SignalingMetrics("call-secret-"+UUID.randomUUID(),SignalingMetrics.Plane.ACTOR,"a".repeat(64))).isInstanceOf(IllegalArgumentException.class);String parent="00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01";assertThat(TraceContext.parse(parent).orElseThrow().header()).isEqualTo(parent);assertThat(TraceContext.parse("00-"+"0".repeat(32)+"-"+"1".repeat(16)+"-01")).isEmpty();assertThat(TraceContext.parse(parent+"-token")).isEmpty();assertThat(TraceContext.attributes(Map.of("userId","sensitive","callId","sensitive","durationNanos",5L))).containsEntry("durationNanos",5L).doesNotContainKeys("userId","callId");}
    @Test void productionLogLayoutDropsSdkMessagesArgumentsAndThrowableSecrets(){var event=new ch.qos.logback.classic.spi.LoggingEvent();event.setLoggerName("io.webrtc.signaling.gateway.AuthHandler");event.setLevel(ch.qos.logback.classic.Level.ERROR);event.setMessage("Bearer aaa.bbb.ccc v=0 candidate:10.0.0.1 TURNpassword=secret");event.setArgumentArray(new Object[]{"another-secret"});event.setThrowableProxy(new ch.qos.logback.classic.spi.ThrowableProxy(new IllegalArgumentException("JWT aaa.bbb.ccc")));var layout=new PrivacySafeLogbackLayout();String output=layout.doLayout(event);assertThat(output).doesNotContain("aaa.bbb.ccc","10.0.0.1","TURNpassword","another-secret").contains("GATEWAY","ERROR");}
    @Test void dashboardsAndBurnAlertsCoverAllQuantilesAndDistinctRecoverySlis()throws Exception{String dashboard=java.nio.file.Files.readString(java.nio.file.Path.of("../deploy/helm/signaling/dashboards/signaling-overview.json"));new com.fasterxml.jackson.databind.ObjectMapper().readTree(dashboard);assertThat(dashboard).contains("0.95","0.99","0.999","WORKFLOW_CONVERGENCE","ACTIVE_CALL_PRESERVATION","SIGNALING_REATTACHMENT","MEDIA_CONTINUITY","OLDEST_UNRECONCILED").doesNotContain("userId","callId");String alerts=java.nio.file.Files.readString(java.nio.file.Path.of("../deploy/helm/signaling/alerts/signaling-rules.yaml"));assertThat(alerts).contains("SignalingFastBurn","SignalingSlowBurn","SERVICE_FAILURE","REVOCATION","OLDEST_UNRECONCILED","5m","1h","6h");}
    @Test void relayHistogramAndConfiguredSecurityBoundAreIndependentOfControlCounts(){try(var metrics=new SignalingMetrics("c001",SignalingMetrics.Plane.GATEWAY,"c".repeat(64))){metrics.relay(SignalingMetrics.RelayOutcome.WRITE_COMPLETED,Duration.ofMillis(3));metrics.securityHardBound(Duration.ofSeconds(5));assertThat(metrics.scrape()).contains("signaling_relay_latency_seconds_bucket","signaling_security_hard_bound_seconds").contains("5.0");assertThat(metrics.businessOutcomes()).isZero();assertThatThrownBy(()->metrics.securityHardBound(Duration.ofSeconds(6))).isInstanceOf(IllegalArgumentException.class);}}
}
