package io.webrtc.signaling.protocol;

public enum ErrorCode {
  UNAUTHENTICATED,
  TOKEN_EXPIRED,
  WRONG_CELL,
  SESSION_REPLACED,
  SESSION_LIMIT,
  USER_BUSY,
  USER_UNAVAILABLE,
  CALL_NOT_FOUND,
  FORBIDDEN,
  STALE_NEGOTIATION,
  INVALID_STATE,
  RATE_LIMITED,
  OVERLOADED,
  RESYNC_REQUIRED,
  OUTCOME_UNKNOWN,
  IDEMPOTENCY_CONFLICT,
  RESULT_EXPIRED,
  ACTIVATION_FAILED,
  SELF_CALL_NOT_ALLOWED,
  RETRYABLE_CONFLICT,
  INVALID_FRAME,
  UNSUPPORTED_PROTOCOL,
  SECURITY_REVOKED
}
