package io.webrtc.signaling.rpc;
import io.webrtc.signaling.protocol.internal.*;
import io.grpc.*;
import io.grpc.netty.NettyChannelBuilder;
import io.grpc.stub.StreamObserver;
import io.netty.handler.ssl.SslContext;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;
/** Two lazy channels/destination, isolated flow control, one owner of bounded same-identity retry. */
public final class CellRpcClient implements AutoCloseable {
    public record Endpoint(String host,int port,String tlsAuthority){public Endpoint{if(host==null||host.isBlank()||port<1||port>65535||tlsAuthority==null||tlsAuthority.isBlank())throw new IllegalArgumentException("Invalid trusted RPC endpoint");}}
    private record ChannelKey(String cell,RpcAdmission.Lane lane) {}
    private final Map<String,Endpoint> destinations;private final RpcTlsContexts.ClientTls tls;private final String environment;private final RpcAdmission admission;private final ConcurrentHashMap<ChannelKey,ManagedChannel> channels=new ConcurrentHashMap<>();private volatile boolean closed;
    private final ExecutorService callbacks=new ThreadPoolExecutor(4,4,0,TimeUnit.SECONDS,new ArrayBlockingQueue<>(256),Thread.ofPlatform().daemon().name("cell-rpc-client-",0).factory(),new ThreadPoolExecutor.AbortPolicy());
    /** Test-only raw context adapter; production supplies cell-bound handshake verification. */
    CellRpcClient(Map<String,Endpoint> destinations,SslContext tls,RpcAdmission admission){this("test",destinations,cell->tls,admission);}
    public CellRpcClient(String environment,Map<String,Endpoint> destinations,RpcTlsContexts.ClientTls tls,RpcAdmission admission){if(environment==null||!environment.matches("[a-z0-9-]{1,32}")||destinations.isEmpty()||destinations.size()>50||destinations.keySet().stream().anyMatch(c->!c.matches("[a-z][a-z0-9-]{0,23}")))throw new IllegalArgumentException("Invalid bounded destination topology");this.environment=environment;this.destinations=Map.copyOf(destinations);this.tls=Objects.requireNonNull(tls);this.admission=Objects.requireNonNull(admission);}
    public int channelCount(){return channels.size();}
    private ManagedChannel channel(String cell,RpcAdmission.Lane lane){Endpoint endpoint=destinations.get(cell);if(endpoint==null)throw new IllegalArgumentException("Unknown destination");return channels.computeIfAbsent(new ChannelKey(cell,lane),key->NettyChannelBuilder.forAddress(endpoint.host(),endpoint.port()).overrideAuthority(endpoint.tlsAuthority()).sslContext(tls.context(cell)).disableRetry().maxInboundMessageSize(98304).executor(callbacks).intercept(new ClientInterceptor(){@Override public <Q,A> ClientCall<Q,A> interceptCall(MethodDescriptor<Q,A> method,CallOptions options,Channel next){var delegate=next.newCall(method,options);return new ForwardingClientCall.SimpleForwardingClientCall<>(delegate){@Override public void start(ClientCall.Listener<A> listener,Metadata headers){super.start(new ForwardingClientCallListener.SimpleForwardingClientCallListener<>(listener){boolean rejected;@Override public void onHeaders(Metadata metadata){var peer=RpcTlsIdentity.extract(delegate.getAttributes().get(Grpc.TRANSPORT_ATTR_SSL_SESSION),environment);if(peer==null||!peer.cell().equals(cell)||!peer.role().equals("actor")){rejected=true;delegate.cancel("UNAUTHORIZED",null);}else super.onHeaders(metadata);}@Override public void onMessage(A message){if(!rejected)super.onMessage(message);}@Override public void onClose(Status status,Metadata trailers){super.onClose(rejected?Status.PERMISSION_DENIED.withDescription("UNAUTHORIZED"):status,trailers);}},headers);}};}}).build());}
    public CompletionStage<InternalReply> call(CellRpcServer.Operation op,InternalCommand original,Duration budget){
        if(closed||budget==null||budget.isNegative()||budget.isZero())return CompletableFuture.completedFuture(error(original,"OUTCOME_UNKNOWN"));if(!destinations.containsKey(original.getDestinationCell()))return CompletableFuture.completedFuture(error(original,"WRONG_CELL"));
        var lane=op==CellRpcServer.Operation.RELAY?RpcAdmission.Lane.RELAY:RpcAdmission.Lane.CONTROL;Duration maximum=Duration.ofSeconds(lane==RpcAdmission.Lane.RELAY?1:2);Duration bounded=budget.compareTo(maximum)>0?maximum:budget;bounded=bounded.compareTo(Duration.ofMillis(original.getRemainingBudgetMs()))>0?Duration.ofMillis(original.getRemainingBudgetMs()):bounded;
        RpcAdmission.Ticket ticket;try{ticket=admission.acquire(lane,original.getSerializedSize());}catch(RpcAdmission.Overloaded e){return CompletableFuture.completedFuture(error(original,"OVERLOADED"));}
        var result=new CompletableFuture<InternalReply>();long end=System.nanoTime()+bounded.toNanos();try{attempt(op,original,end,0,lane,result);}catch(RuntimeException e){result.complete(error(original,"OUTCOME_UNKNOWN"));}result.whenComplete((r,e)->ticket.close());return result.minimalCompletionStage();
    }
    private void attempt(CellRpcServer.Operation op,InternalCommand original,long end,int attempt,RpcAdmission.Lane lane,CompletableFuture<InternalReply> result){long remaining=end-System.nanoTime();if(closed||remaining<=0){result.complete(error(original,"OUTCOME_UNKNOWN"));return;}var command=original.toBuilder().setRemainingBudgetMs(Math.max(1,TimeUnit.NANOSECONDS.toMillis(remaining))).build();var stub=CellIngressGrpc.newStub(channel(original.getDestinationCell(),lane)).withDeadlineAfter(remaining,TimeUnit.NANOSECONDS).withWaitForReady();
        var observer=new StreamObserver<InternalReply>(){boolean received;@Override public void onNext(InternalReply value){received=true;if(original.getOperationId().equals(value.getOperationId()))result.complete(value);else result.complete(error(original,"OUTCOME_UNKNOWN"));}@Override public void onCompleted(){if(!received)result.complete(error(original,"OUTCOME_UNKNOWN"));}@Override public void onError(Throwable failure){Status.Code code=Status.fromThrowable(failure).getCode();if(code==Status.Code.UNAVAILABLE&&attempt<2&&end-System.nanoTime()>0){try{CellRpcClient.this.attempt(op,original,end,attempt+1,lane,result);}catch(RuntimeException rejected){result.complete(error(original,"OUTCOME_UNKNOWN"));}}else result.complete(error(original,code==Status.Code.PERMISSION_DENIED||code==Status.Code.UNAUTHENTICATED?"UNAUTHORIZED":"OUTCOME_UNKNOWN"));}};
        switch(op){case RESERVE->stub.reserveUser(command,observer);case CLAIM->stub.claimAccept(command,observer);case RELEASE->stub.releaseIfCallVersion(command,observer);case EXECUTE->stub.executeCallCommand(command,observer);case RELAY->stub.relayNegotiation(command,observer);case SYNC->stub.syncCall(command,observer);default->throw new IllegalArgumentException("Use event delivery method");}
    }
    public CompletionStage<InternalReply> deliver(String destination,ControlEvent event,Duration budget){
        if(closed||!destinations.containsKey(destination)||budget.isNegative()||budget.isZero())return CompletableFuture.completedFuture(InternalReply.newBuilder().setErrorCode("OUTCOME_UNKNOWN").build());RpcAdmission.Ticket ticket;try{ticket=admission.acquire(RpcAdmission.Lane.CONTROL,event.getSerializedSize());}catch(RpcAdmission.Overloaded e){return CompletableFuture.completedFuture(InternalReply.newBuilder().setErrorCode("OVERLOADED").build());}var result=new CompletableFuture<InternalReply>();long nanos=Math.min(budget.toNanos(),Duration.ofSeconds(2).toNanos());try{CellIngressGrpc.newStub(channel(destination,RpcAdmission.Lane.CONTROL)).withDeadlineAfter(nanos,TimeUnit.NANOSECONDS).deliverControlEvent(event,new StreamObserver<>(){@Override public void onNext(InternalReply value){result.complete(value);}@Override public void onError(Throwable e){result.complete(InternalReply.newBuilder().setErrorCode("OUTCOME_UNKNOWN").build());}@Override public void onCompleted(){result.complete(InternalReply.newBuilder().setErrorCode("OUTCOME_UNKNOWN").build());}});}catch(RuntimeException e){result.complete(InternalReply.newBuilder().setErrorCode("OUTCOME_UNKNOWN").build());}result.whenComplete((v,e)->ticket.close());return result.minimalCompletionStage();
    }
    private static InternalReply error(InternalCommand c,String code){return InternalReply.newBuilder().setOperationId(c.getOperationId()).setCallId(c.getCallId()).setStatus("REJECTED").setErrorCode(code).build();}
    @Override public void close(){closed=true;channels.values().forEach(ManagedChannel::shutdown);callbacks.shutdown();}
}
