package io.webrtc.signaling.rpc;
import io.webrtc.signaling.protocol.Identity.*;
import io.webrtc.signaling.protocol.PortableProofTime;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.core.*;
import java.security.*;
import java.time.*;
import java.util.*;
/** Versioned signatures bind the exact authority tuple and business request. Replays do not renew proof expiry. */
public final class HomeAuthorizationProof {
    public record Claims(int schema,String purpose,String sourceCell,String destinationCell,UUID operation,CallId call,UserId user,SessionKey session,SessionIncarnation incarnation,long generation,long directoryEpoch,long storageEpoch,long hashVersion,int group,long groupEpoch,long leaseSequence,UUID ownerIncarnation,UUID reservationId,long reservationVersion,UUID activationId,long callVersion,long negotiationId,String intentHash,Instant issuedAt,Instant expiresAt,long sourceStorageEpoch,Instant participantUntil,@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) UUID connectionId,@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) String sourceAcceptIntentHash){
        public Claims(int schema,String purpose,String sourceCell,String destinationCell,UUID operation,CallId call,UserId user,SessionKey session,SessionIncarnation incarnation,long generation,long directoryEpoch,long storageEpoch,long hashVersion,int group,long groupEpoch,long leaseSequence,UUID ownerIncarnation,UUID reservationId,long reservationVersion,UUID activationId,long callVersion,long negotiationId,String intentHash,Instant issuedAt,Instant expiresAt,long sourceStorageEpoch,Instant participantUntil){this(schema,purpose,sourceCell,destinationCell,operation,call,user,session,incarnation,generation,directoryEpoch,storageEpoch,hashVersion,group,groupEpoch,leaseSequence,ownerIncarnation,reservationId,reservationVersion,activationId,callVersion,negotiationId,intentHash,issuedAt,expiresAt,sourceStorageEpoch,participantUntil,null);}
        public Claims(int schema,String purpose,String sourceCell,String destinationCell,UUID operation,CallId call,UserId user,SessionKey session,SessionIncarnation incarnation,long generation,long directoryEpoch,long storageEpoch,long hashVersion,int group,long groupEpoch,long leaseSequence,UUID ownerIncarnation,UUID reservationId,long reservationVersion,UUID activationId,long callVersion,long negotiationId,String intentHash,Instant issuedAt,Instant expiresAt,long sourceStorageEpoch,Instant participantUntil,UUID connectionId){this(schema,purpose,sourceCell,destinationCell,operation,call,user,session,incarnation,generation,directoryEpoch,storageEpoch,hashVersion,group,groupEpoch,leaseSequence,ownerIncarnation,reservationId,reservationVersion,activationId,callVersion,negotiationId,intentHash,issuedAt,expiresAt,sourceStorageEpoch,participantUntil,connectionId,null);}
        public Claims {if(sourceAcceptIntentHash!=null&&(!purpose.equals("COORDINATOR_GRANT")||!sourceAcceptIntentHash.matches("[0-9a-f]{64}")))throw new IllegalArgumentException("Invalid ACCEPT consent binding");if(schema!=1||!Set.of("COORDINATOR_GRANT","SESSION","WINNER","ACTIVE","TARGET_ROUTE").contains(purpose)||!cell(sourceCell)||!cell(destinationCell)||operation==null||call==null||user==null||directoryEpoch<1||storageEpoch<1||sourceStorageEpoch<1||hashVersion!=1||group<0||group>1023||groupEpoch<1||leaseSequence<1||ownerIncarnation==null||generation<0||reservationVersion<0||callVersion<0||negotiationId<0||session!=null&&(incarnation==null||generation<1)||intentHash==null||!intentHash.matches("[0-9a-f]{64}")||issuedAt==null||expiresAt==null||!expiresAt.isAfter(issuedAt)||Duration.between(issuedAt,expiresAt).compareTo(Duration.ofSeconds(5))>0)throw new IllegalArgumentException("Invalid home authorization proof");}
    }
    private static final ObjectMapper JSON=new ObjectMapper(JsonFactory.builder().streamReadConstraints(StreamReadConstraints.builder().maxNestingDepth(16).maxStringLength(4096).build()).enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).build()).findAndRegisterModules().enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
    private final String cell,keyId;private final PrivateKey signingKey;private final Map<String,PublicKey> trusted;
    public HomeAuthorizationProof(String cell,String keyId,PrivateKey signingKey,Map<String,PublicKey> trusted){if(!cell(cell)||keyId==null||!keyId.matches("[A-Za-z0-9_-]{1,64}")||trusted.size()>256)throw new IllegalArgumentException("Invalid proof key configuration");this.cell=cell;this.keyId=keyId;this.signingKey=Objects.requireNonNull(signingKey);this.trusted=Map.copyOf(trusted);if(!"EdDSA".equals(signingKey.getAlgorithm())&&!"Ed25519".equals(signingKey.getAlgorithm()))throw new IllegalArgumentException("Ed25519 signing key required");}
    public RelaySessionAuthorizationProof relaySessionProofs(){return new RelaySessionAuthorizationProof(cell,keyId,signingKey,trusted);}
    public SessionAuthorizationProof sessionProofs(){return new SessionAuthorizationProof(cell,keyId,signingKey,trusted);}
    public String sourceCell(){return cell;}
    public String issue(Claims claims){if(!cell.equals(claims.sourceCell()))throw new IllegalArgumentException("Cannot sign another cell's proof");try{String payload=Base64.getUrlEncoder().withoutPadding().encodeToString(JSON.writeValueAsBytes(claims));String unsigned=cell+"."+keyId+"."+payload;var signer=Signature.getInstance("Ed25519");signer.initSign(signingKey);signer.update(unsigned.getBytes(java.nio.charset.StandardCharsets.US_ASCII));String token=unsigned+"."+Base64.getUrlEncoder().withoutPadding().encodeToString(signer.sign());if(token.length()>4096)throw new IllegalArgumentException("Proof exceeds bound");return token;}catch(GeneralSecurityException|java.io.IOException invalid){throw new IllegalArgumentException("Cannot issue proof",invalid);}}
    public boolean verify(String signed,Claims expected,String authenticatedSourceCell,Instant now){return decode(signed,authenticatedSourceCell,now).filter(expected::equals).isPresent();}
    public Optional<Claims> decode(String signed,String authenticatedSourceCell,Instant now){
        try{if(signed==null||signed.length()>4096||now==null)return Optional.empty();String[] parts=signed.split("\\.",-1);if(parts.length!=4||!parts[0].equals(authenticatedSourceCell)||!cell(parts[0])||!parts[1].matches("[A-Za-z0-9_-]{1,64}")||!parts[2].matches("[A-Za-z0-9_-]+")||!parts[3].matches("[A-Za-z0-9_-]{86}"))return Optional.empty();var key=trusted.get(parts[0]+"/"+parts[1]);if(key==null)return Optional.empty();var verifier=Signature.getInstance("Ed25519");verifier.initVerify(key);verifier.update((parts[0]+"."+parts[1]+"."+parts[2]).getBytes(java.nio.charset.StandardCharsets.US_ASCII));if(!verifier.verify(Base64.getUrlDecoder().decode(parts[3])))return Optional.empty();var claims=JSON.readValue(Base64.getUrlDecoder().decode(parts[2]),Claims.class);if(!parts[0].equals(claims.sourceCell())||!PortableProofTime.valid(claims.issuedAt(),claims.expiresAt(),now))return Optional.empty();return Optional.of(claims);}catch(Exception invalid){return Optional.empty();}
    }
    private static boolean cell(String value){return value!=null&&value.matches("[a-z][a-z0-9-]{0,23}");}
}
