package io.webrtc.signaling.rpc;
import io.webrtc.signaling.protocol.*;
import io.webrtc.signaling.protocol.Identity.*;
import io.webrtc.signaling.protocol.internal.*;
import io.webrtc.signaling.storage.*;
import io.webrtc.signaling.storage.HomeParticipationService.*;
import io.webrtc.signaling.actors.user.UserCommand;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.core.*;
import com.google.protobuf.ByteString;
import java.nio.ByteBuffer;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Function;
/** Authenticated RPC -> typed sharding facade. Effects recheck native authority; ingress never performs SQL. */
public final class RpcBusinessHandler implements CellRpcServer.Backend {
    public record UserPayload(UserCommand.Operation operation,String sessionProof){public UserPayload{Objects.requireNonNull(operation);if(sessionProof!=null&&sessionProof.length()>4096)throw new IllegalArgumentException("Oversized session proof");}}
    public record CallPayload(CallCommand command,String proof){public CallPayload{Objects.requireNonNull(command);if(proof==null||proof.length()>8192)throw new IllegalArgumentException("Invalid command proof");}}
    public record WorkflowPayload(CallWorkflowService.Transition transition) {}
    public record SyncRead(AuthenticatedSession sender,CallId call,RequestId request,String proof,String intentHash) {}
    public record RelayRequest(InternalCommand command,CellRpcServer.Peer peer,Duration budget) {}
    public interface ActorIngress {
        CompletionStage<UserCommand.Result> user(UserCommand.Operation operation,Instant deadline,int bytes);
        CompletionStage<CallCommandService.Outcome> call(CallCommand command,String proof,Instant deadline,int bytes);
        CompletionStage<CallWorkflowService.Outcome> progress(CallWorkflowService.Transition transition,Instant deadline,int bytes);
    }
    private static final ObjectMapper JSON=new ObjectMapper(JsonFactory.builder().streamReadConstraints(StreamReadConstraints.builder().maxNestingDepth(16).maxStringLength(81920).maxNumberLength(64).build()).enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).build()).findAndRegisterModules().enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
    private final String cell;private final ActorIngress actors;private final ProofBindings bindings;private final HomeAuthorizationProof proofs;private final Function<UserId,ProofBindings.TrustedHome> homes;private final Function<SyncRead,CompletionStage<CallSnapshotRepository.Snapshot>> reads;private final Function<RelayRequest,CompletionStage<InternalReply>> relay;private final Clock clock;
    public RpcBusinessHandler(String cell,ActorIngress actors,ProofBindings bindings,HomeAuthorizationProof proofs,Function<UserId,ProofBindings.TrustedHome> homes,Function<SyncRead,CompletionStage<CallSnapshotRepository.Snapshot>> reads,Function<RelayRequest,CompletionStage<InternalReply>> relay,Clock clock){this.cell=Objects.requireNonNull(cell);this.actors=Objects.requireNonNull(actors);this.bindings=Objects.requireNonNull(bindings);this.proofs=Objects.requireNonNull(proofs);this.homes=Objects.requireNonNull(homes);this.reads=Objects.requireNonNull(reads);this.relay=Objects.requireNonNull(relay);this.clock=Objects.requireNonNull(clock);}
    public static byte[] encode(Object payload){try{byte[] value=JSON.writeValueAsBytes(payload);if(value.length>81920)throw new IllegalArgumentException("Oversized RPC payload");return value;}catch(java.io.IOException invalid){throw new IllegalArgumentException("Invalid RPC DTO",invalid);}}
    private static <T>T decode(InternalCommand c,Class<T> type)throws java.io.IOException {if(c.getPayload().size()>81920)throw new IllegalArgumentException("Oversized RPC DTO");return JSON.readValue(c.getPayload().toByteArray(),type);}
    @Override public CompletionStage<InternalReply> execute(CellRpcServer.Operation op,InternalCommand c,CellRpcServer.Peer peer,Duration budget){
        try{if(peer==null||!cell.equals(c.getDestinationCell())||budget.isNegative()||budget.isZero()||c.getSerializedSize()>98304||c.getPayloadHash().size()!=32||c.getSchemaMajor()!=1||c.getSchemaMinor()<0||c.getSchemaMinor()>1)throw new IllegalArgumentException("Invalid business envelope");UUID operation=UUID.fromString(c.getOperationId());var call=new CallId(c.getCallId());if(!CommandScope.call(call).value().equals(c.getCommandScope())&&!CommandScope.invite().value().equals(c.getCommandScope()))throw new IllegalArgumentException("Invalid routed scope");Instant deadline=clock.instant().plus(budget);int bytes=c.getSerializedSize();
            if(Set.of(CellRpcServer.Operation.RESERVE,CellRpcServer.Operation.CLAIM,CellRpcServer.Operation.RELEASE).contains(op)||op==CellRpcServer.Operation.EXECUTE&&Set.of("RenewReservation","ConfirmActivation").contains(c.getType())){
                if(!peer.role().equals("actor"))return rejected(c,"UNAUTHORIZED");var payload=decode(c,UserPayload.class);Request request=request(payload.operation());var action=action(payload.operation());
                boolean matches=switch(op){case RESERVE->c.getType().equals("ReserveUser")&&payload.operation() instanceof UserCommand.Reserve;case CLAIM->c.getType().equals("ClaimAccept")&&payload.operation() instanceof UserCommand.Accept;case RELEASE->c.getType().equals("ReleaseIfCallVersion")&&payload.operation() instanceof UserCommand.Release;case EXECUTE->c.getType().equals("RenewReservation")&&payload.operation() instanceof UserCommand.Renew||c.getType().equals("ConfirmActivation")&&payload.operation() instanceof UserCommand.Activate;default->false;};
                if(!matches||!call.equals(request.call())||!operation.equals(request.grant().operation())||!peer.cell().equals(request.grant().cell())||!bindings.homeVerifier(cell).verify(request,action)||!HexFormat.of().formatHex(c.getPayloadHash().toByteArray()).equals(HomeParticipationService.authorizationHash(request,action)))return rejected(c,"UNAUTHORIZED");
                var signed=proofs.decode(request.grant().proof(),peer.cell(),clock.instant()).orElseThrow();var authority=c.getAuthority();if(!authority.getCellId().equals(signed.sourceCell())||authority.getStorageEpoch()!=signed.storageEpoch()||authority.getOwnershipHashVersion()!=signed.hashVersion()||authority.getGroupId()!=signed.group()||authority.getGroupEpoch()!=signed.groupEpoch()||authority.getLeaseSequence()!=signed.leaseSequence()||!uuid(authority.getOwnerIncarnation()).equals(signed.ownerIncarnation()))return rejected(c,"UNAUTHORIZED");
                if(payload.operation() instanceof UserCommand.Accept accept&&!currentSessionProof(payload.sessionProof(),accept.route(),call,operation,HomeParticipationService.authorizationHash(request,action)))return rejected(c,"UNAUTHORIZED");
                return actors.user(payload.operation(),deadline,bytes).thenApply(result->{String code=result.code().name();boolean committed=Set.of("RESERVED","RENEWED","RELEASED","CLAIMED","CONFIRMED","ANSWERED_ELSEWHERE","TERMINAL").contains(code);return reply(c,committed,code,result);});
            }
            if(op==CellRpcServer.Operation.EXECUTE&&c.getType().equals("WorkflowStep")){
                if(!peer.role().equals("actor")||!peer.cell().equals(cell)||!call.coordinatorCell().equals(cell))return rejected(c,"UNAUTHORIZED");var payload=decode(c,WorkflowPayload.class);var transition=payload.transition();if(!call.equals(transition.call())||!operation.equals(transition.operation())||!transition.group().cell().equals(cell)||transition.expectedVersion()!=c.getExpectedCallVersion()||!ProofBindings.workflowIntent(transition).equals(HexFormat.of().formatHex(c.getPayloadHash().toByteArray())))return rejected(c,"UNAUTHORIZED");return actors.progress(transition,deadline,bytes).thenApply(value->reply(c,!Set.of("UNKNOWN","UNAVAILABLE","FENCED","OVERLOADED","EXPIRED","INVALID").contains(value.code()),value.code(),value));
            }
            if(op==CellRpcServer.Operation.EXECUTE){var payload=decode(c,CallPayload.class);var command=payload.command();var home=homes.apply(command.sender().userId());if(home==null||!peer.cell().equals(home.cell())||!call.coordinatorCell().equals(cell)||!call.equals(command.callId())||!operation.equals(command.requestId().value())||!c.getType().equals(command.type().name())||!c.getCommandScope().equals(command.scope().value())||!command.intentHash().equals(HexFormat.of().formatHex(c.getPayloadHash().toByteArray()))||!bindings.commandVerifier(cell,homes).verify(command,null,payload.proof())||!sameSender(c.getSender(),command.sender()))return rejected(c,"UNAUTHORIZED");return actors.call(command,payload.proof(),deadline,bytes).thenApply(value->reply(c,value.status().equals("FINAL"),value.code(),value));}
            if(op==CellRpcServer.Operation.SYNC){var read=decode(c,SyncRead.class);var command=new CallCommand(SignalEnvelope.Type.SYNC_CALL,read.sender(),read.request(),read.call(),CommandScope.call(read.call()),null,null,null,"{}",read.intentHash());var home=homes.apply(read.sender().userId());if(home==null||!peer.cell().equals(home.cell())||!call.equals(read.call())||!operation.equals(read.request().value())||!bindings.commandVerifier(cell,homes).verify(command,null,read.proof())||!sameSender(c.getSender(),read.sender()))return rejected(c,"UNAUTHORIZED");return reads.apply(read).thenApply(snapshot->reply(c,false,"SNAPSHOT",snapshot));}
            if(op==CellRpcServer.Operation.RELAY)return relay.apply(new RelayRequest(c,peer,budget));return rejected(c,"UNSUPPORTED_OPERATION");
        }catch(Exception invalid){return rejected(c,"UNAUTHORIZED");}
    }
    private boolean currentSessionProof(String signed,SessionRepository.Route route,CallId call,UUID operation,String intent){return proofs.decode(signed,cell,clock.instant()).filter(p->p.purpose().equals("SESSION")&&p.destinationCell().equals(cell)&&p.call().equals(call)&&p.user().equals(route.user())&&Objects.equals(p.session(),route.key())&&Objects.equals(p.incarnation(),route.incarnation())&&p.generation()==route.connectionGeneration()&&p.operation().equals(operation)&&p.intentHash().equals(intent)).isPresent();}
    private static boolean sameSender(SessionIdentity wire,AuthenticatedSession sender){return wire.getUserId().equals(sender.userId().value())&&wire.getIssuer().equals(sender.key().issuer())&&wire.getJti().equals(sender.key().jti())&&wire.getConnectionGeneration()==sender.connectionGeneration()&&uuid(wire.getIncarnation()).equals(sender.incarnation().value())&&uuid(wire.getConnectionId()).equals(sender.connectionId());}
    static UUID uuid(ByteString bytes){if(bytes.size()!=16)throw new IllegalArgumentException("Invalid UUID wire field");var b=bytes.asReadOnlyByteBuffer();return new UUID(b.getLong(),b.getLong());}
    public static Request request(UserCommand.Operation operation){return switch(operation){case UserCommand.Reserve r->r.request();case UserCommand.Renew r->r.request();case UserCommand.Release r->r.request();case UserCommand.Accept r->r.request();case UserCommand.Activate r->r.request();default->throw new IllegalArgumentException("Session registration requires its authenticated home ingress");};}
    public static AuthorizationIntent action(UserCommand.Operation operation){return switch(operation){case UserCommand.Reserve r->AuthorizationIntent.reserve();case UserCommand.Renew r->new AuthorizationIntent("RENEW",r.reservation(),r.version(),null,0,null,null);case UserCommand.Release r->new AuthorizationIntent("RELEASE",r.reservation(),r.version(),null,0,null,null);case UserCommand.Accept r->new AuthorizationIntent("CLAIM",r.reservation(),0,null,0,null,r.route());case UserCommand.Activate r->new AuthorizationIntent("CONFIRM",r.reservation(),r.version(),r.activation(),r.callVersion(),r.winner(),null);default->throw new IllegalArgumentException("Invalid home operation");};}
    private static CompletionStage<InternalReply> rejected(InternalCommand c,String code){return CompletableFuture.completedFuture(reply(c,false,code,null));}
    private static InternalReply reply(InternalCommand c,boolean committed,String code,Object value){var builder=InternalReply.newBuilder().setOperationId(c.getOperationId()).setCallId(c.getCallId()).setAckCommitted(committed).setStatus(committed?"COMMITTED":"PENDING");if(!committed&&!code.equals("SNAPSHOT"))builder.setErrorCode(code);if(value!=null)builder.setResult(ByteString.copyFrom(encode(value)));return builder.build();}
}
